---
abstract: 'Software deployment support'
build_requires:
  ExtUtils::MakeMaker: 6.59
  POE::Component::Client::Ping: 0
  Test::Compile: 0
  Test::HTTP::Server::Simple: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FusionInventory-Agent-Task-Deploy
no_index:
  directory:
    - inc
    - t
recommends:
  POE::Component::Client::Ping: 0
requires:
  Archive::Extract: 0
  Digest::SHA: 0
  File::Copy::Recursive: 0
  JSON: 0
  URI::Escape: 0
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 2.0.0
